Rails.application.routes.draw do
  devise_for :users
  resources :excluded_strategem_keywords
  resources :squad_leaders
  resources :wargear_options
  resources :games_secondary_objectives
  resources :mission_rules
  resources :terrain_layouts
  resources :deployments
  resources :friends
  resources :games
  resources :lists
  resources :keywords
  resources :enhancement_keywords
  resources :enhancements
  resources :abilities
  resources :model_keywords
  resources :strategem_keywords
  resources :strategems
  resources :available_strategems
  resources :weapon_abilities
  resources :weapons
  resources :model_weapons
  resources :models
  resources :units
  resources :detachments
  resources :armies

  root "homes#home"
end
